[package]
name = "pokereval_cactus_rs"
version = "0.1.0"
authors = ["goniX <hargonix@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
rand = "0.6.5"
itertools = "0.8.0"

[dependencies.pyo3]
version = "0.7.0-alpha.1"
features = ["extension-module"]
